# name: Blue-Green Inference Deployment Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-green:
    name: 1. Deploy Green Candidate
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying new 'green' version to the cluster..."
          echo "COMMAND: helm upgrade --install inference-service ./helm/inference-service --set green.tag=$GITHUB_SHA"
          echo "Green version is live for internal testing."

  test-green:
    name: 2. Run Performance Tests on Green
    runs-on: ubuntu-latest
    needs: deploy-green
    steps:
      - uses: actions/checkout@v3
      - name: Run performance test script
        run: ./scripts/run-perf-test.sh

  promote-to-live:
    name: 3. Promote Green to Live Traffic
    runs-on: ubuntu-latest
    needs: test-green
    steps:
      - run: |
          echo "PROMOTING GREEN TO LIVE..."
          echo "This is the atomic switch. We patch the live service to change its selector."
          echo "COMMAND: helm upgrade --install inference-service ./helm/inference-service --set liveColor=green"
          echo "Production traffic is now flowing to the green deployment."

  teardown-old-blue:
    name: 4. Teardown Old Blue Deployment
    runs-on: ubuntu-latest
    needs: promote-to-live
    steps:
      - run: |
          echo "Cleaning up old blue deployment to save resources..."
          echo "COMMAND: kubectl delete deployment inference-service-blue"
          echo "Cleanup complete."
