name: Blue-Green Inference Deployment Validation

on:
  workflow_dispatch:

jobs:
  validate-and-deploy-green:
    name: "1. Validate and Deploy Green Candidate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Lint Helm Chart
        run: helm lint ./helm/inference-service

      - name: Template Green Deployment to Verify
        run: |
          echo "Verifying the 'green' deployment configuration..."
          helm template ./helm/inference-service --set image.tag=1.1.0
          echo "Green deployment configuration is valid."

  test-green:
    name: "2. Run Performance & Validation Tests"
    runs-on: ubuntu-latest
    needs: validate-and-deploy-green
    steps:
      - uses: actions/checkout@v3
      - name: Make script executable # <--- THIS IS THE FIX
        run: chmod +x ./scripts/run-perf-test.sh
      - name: Run performance test script
        run: ./scripts/run-perf-test.sh

  promote-to-live:
    name: "3. ✅ Validate Promotion to Live"
    runs-on: ubuntu-latest
    needs: test-green
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: "VALIDATE THE MAGIC SWITCH: Template the chart with liveColor=green"
        run: |
          echo "--- BEFORE THE SWITCH (Default state) ---"
          helm template ./helm/inference-service | grep -A 2 "kind: Service"
          echo "----------------------------------------"
          echo ""
          echo "--- AFTER THE SWITCH (Promoted state) ---"
          helm template ./helm/inference-service --set liveColor=green | grep -A 2 "kind: Service"
          echo "----------------------------------------"
          echo ""
          echo "PROOF: The Service selector has successfully switched to 'green'!"

  teardown-old-blue:
    name: "4. 🧹 Simulate Teardown"
    runs-on: ubuntu-latest
    needs: promote-to-live
    steps:
      - name: Simulate Cleaning Up Old Deployment
        run: echo "Cleanup of old 'blue' deployment would run here."
